#2-5
import turtle,random
h=random.randint(1,100)
j=random.randint(1,360)
l=random.randint(1,100)
f=random.randint(1,360)
fourfour = turtle.Turtle()
fourfour.color('blue')
fivefive=turtle.Turtle()
fivefive.color('red')
while True:
    fourfour.forward(h)
    fourfour.left(j)
    h=random.randint(1,100)
    j=random.randint(1,360)
    fourfour.forward(h)
    fourfour.right(j)
    h=random.randint(1,100)
    j=random.randint(1,360)
    fivefive.forward(h)
    fivefive.left(j)
    l=random.randint(1,100)
    f=random.randint(1,360)
    fivefive.forward(h)
    fivefive.right(j)
    l=random.randint(1,100)
    f=random.randint(1,360)
